### ISSUE TITLE
A question about "Go, Lint. Go! How to Build a Go Linting Rule"

### ISSUE THREAD

**Issue by preslavrachev** [dustinspecker/dustinspecker.com#14]
Hi @dustinspecker,

I have just stumbled upon your fantastic guide, and I can't help but thank you. I have been thinking of creating a set of opinionated linters and style checkers for our internal Go projects and this guide was just perfect.

I have one question, though. While I had zero issues building the linter as an executable, I could not help but wonder, if I could somehow attach that executable to VS Code. I want to be able to see warning messages right there, as I safe my Go file. We use `golang-ci-lint` for our projects. Do you know of any way to attach another linter executable to it somehow?

Regards,
Preslav

**Comment by dustinspecker** [comment]
Thank you for the kind words! It means a lot to read that @preslavrachev. 

I've also wondered how to add internal/private plugins to `golangci-lint`. I'm unsure how to add the compiled binaries to be used by VS Code. But I've been exploring how to add private plugins to `golangci-lint` itself. That might work for VS Code, then.

This question finally got me to start poking around at adding private plugins to `golangci-lint` :) This may be an option for you all.

https://golangci-lint.run/contributing/new-linters/  Thankfully, golangci-lint has a great starting point for private linters.

1. Start with https://github.com/dustinspecker/go-lint-rule-demo as-is
2. Align `go.mod` versions with the versions used by `golangci-lint`. I'm using `golangci-lint` version v1.55.2, so the respective `go.mod` is https://github.com/golangci/golangci-lint/blob/v1.55.2/go.mod
3. Update https://github.com/dustinspecker/go-lint-rule-demo's `go.mod` to use `v0.14.0` instead of `v0.5.0` for `golang.org/x/tools`
4. Run `go mod tidy` for `go-lint-rule-demo`
5. Create a new directory in `go-lint-rule-demo` named `plugin`
6. Create a new file `plugin/main.go` with the following content:

```go
package main

import (
	"go-lint-rule-demo/internal/rules"

	"golang.org/x/tools/go/analysis"
)

func New(_ any) ([]*analysis.Analyzer, error) {
	return []*analysis.Analyzer{
		rules.NoFmtPrintf,
	}, nil
}
```

7. Build a plugin as described in golangci-lint's docs: `go build -buildmode=plugin ./plugin/main.go` to create a `main.so` file
8. Create a `.golangci.yaml` configuration file with the following content:
```yaml
linters-settings:
  custom:
    nofmtprintf:
      path: ./main.so
      description: forbid fmt.Printf usage
      original-url: github.com/dustinspecker/go-lint-rule-demo
```
9. Then we can run `golangci-lint` from the root of `go-lint-rule-demo` like `golangci-lint run  ./internal/rules/testdata/src/nofmtprintf` to see the following output:

```
internal/rules/testdata/src/nofmtprintf/example.go:9:6: func `dostuff` is unused (unused)
func dostuff() {
     ^
internal/rules/testdata/src/nofmtprintf/example.go:20:6: type `printer` is unused (unused)
type printer struct{}
     ^
internal/rules/testdata/src/nofmtprintf/example.go:22:16: func `printer.Printf` is unused (unused)
func (printer) Printf(string)  {}
               ^
internal/rules/testdata/src/nofmtprintf/example.go:23:16: func `printer.Println` is unused (unused)
func (printer) Println(string) {}
               ^
internal/rules/testdata/src/nofmtprintf/example.go:10:2: Don't use fmt.Printf (nofmtprintf)
	fmt.Printf("hello")    // want `Don't use fmt.Printf`
	^
internal/rules/testdata/src/nofmtprintf/example.go:11:2: Don't use fmt.Printf (nofmtprintf)
	format.Printf("hello") // want `Don't use fmt.Printf`
	^
internal/rules/testdata/src/nofmtprintf/example.go:12:2: Don't use fmt.Printf (nofmtprintf)
	Printf("hello")        // want `Don't use fmt.Printf`
	^
```

Definitely going to depend a lot on your use cases. Where I work, we have a container image we build with `golangci-lint` installed, so it's not unreasonable for us to include custom-built plugins in that. If it's feasible for developers to build the plugins locally as part of the development environment setup, then this might work out for VS Code integration.

Thank you for bringing this up! I'm happy to have found out it isn't too bad using one of these linters in `golangci-lint`. Please let me know if you all figure out a nice solution for VS Code without these hoops.
